site_name: 'backstage-app Docuemtation'
site_description: 'site description'

nav:
  - Home: index.md
  - SubDocs: '!include ./sub-docs/mkdocs.yml'
  - Plugins: '*include ./plugins/*/mkdocs.yml'

plugins:
  - techdocs-core